export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATE = "USER UPDATED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const EMAIL_VERIFIED = "EMAIL_VERIFIED";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED";
export const FILTERED_USER_LIST_LOADED = "FILTERED_USER_LIST_LOADED";
export const PASSWORD_RESET_LINK_VALID = "PASSWORD_RESET_LINK_VALID";
export const RESET_PASSWORD_LINK_SENT = "RESET_PASSWORD_LINK_SENT";
export const RESET_PASSWORD_LINK_FAILED = "RESET_PASSWORD_LINK_FAILED";
export const SUBMIT_NEW_PASSWORD_SUCCESS = "SUBMIT_NEW_PASSWORD_SUCCESS";
export const SUBMIT_NEW_PASSWORD_FAIL = "SUBMIT_NEW_PASSWORD_FAIL";
export const API_KEY_LOADED = "API_KEY_LOADED";
export const SOCIALS_UPDATED = "SOCIALS_UPDATED";
export const RESET_UPDATED_SOCIALS = "RESET_UPDATED_SOCIALS";
export const ACCOUNT_SUCCESSFUL_DELETED = "ACCOUNT_SUCCESSFUL_DELETED";
export const SET_NOTIFICATION_DATA = "SET_NOTIFICATION_DATA";
export const RESET_NOTIFICATION_DATA = "RESET_NOTIFICATION_DATA";
export const PASSWORD_RESET_SUCCESS_FLAG_RESETTED =
  "PASSWORD_RESET_SUCCESS_FLAG_RESETTED";

export const LOAD_COMPETITORS = "GET_COMPETITORS";

export const ORGANIZATION_CREATED = "ORGANIZATION_CREATED";
export const ORGANIZATION_CREATION_FAIL = "ORGANIZATION_CREATION_FAIL";
export const ORGANIZATION_LIST_LOADED = "ORGANIZATION_LIST_LOADED";
export const ORGANIZATION_IS_LOADING = "ORGANIZATION_IS_LOADING";
export const ORGANIZATION_LOADED = "ORGANIZATION_LOADED";
export const GET_SELECTED_ORGANIZATION = "GET_SELECTED_ORGANIZATION";
export const ORGANIZATION_SELECTED = "ORGANIZATION_SELECTED";
export const ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED";
export const ALL_ORGANIZATION_LIST_LOADED = "ALL_ORGANIZATION_LIST_LOADED";
export const SET_SELECTED_FOLLOWED_ORGANIZATION =
  "SET_SELECTED_FOLLOWED_ORGANIZATION";
export const FILTER_FOR_EVENTS_UPDATED = "FILTER_FOR_EVENTS_UPDATED";
export const RESET_IS_CREATED = "RESET_IS_CREATED";
export const RESET_FILTERED_HOME_ORGANIZATION =
  "RESET_FILTERED_HOME_ORGANIZATION";
export const FOUND_ORG_SELECTED = "FOUND_ORG_SELECTED";
export const HOME_ORGANIZATION_SELECTED = "HOME_ORGANIZATION_SELECTED";
export const HOME_ORGANIZATION_LOADED = "HOME_ORGANIZATION_LOADED";
export const OWNER_REQUEST_SENT = "OWNER_REQUEST_SENT";
export const YOUR_ORGANIZATION_LIST_IS_LOADING =
  "YOUR_ORGANIZATION_LIST_IS_LOADING";
export const ORGANIZATION_LOCATION_UPDATED = "ORGANIZATION_LOCATION_UPDATED";
export const ORGANIZATION_ADMIN_REQUESTS_LOADED =
  "ORGANIZATION_ADMIN_REQUESTS_LOADED";
export const POINTS_UPDATED = "POINTS_UPDATED";
export const RESET_POINTS_UPDATED = "RESET_POINTS_UPDATED";
export const STREAM_LINK_SELECTED = "STREAM_LINK_SELECTED";
export const ORGANIZATION_STREAM_LINK_UPDATED =
  "ORGANIZATION_STREAM_LINK_UPDATED";

export const LEADERBOARD_CREATED = "LEADERBOARD_CREATED";
export const RESET_LEADERBOARD = "RESET_LEADERBOARD";
export const ALL_LEADERBOARDS_LOADED = "ALL_LEADERBOARDS_LOADED";
export const LEADERBOARD_DELETED = "LEADERBOARD_DELETED";

export const RESET_TEAM_IS_CREATED = "RESET_TEAM_IS_CREATED";
export const RESET_TEAM_IS_DELETED = "RESET_TEAM_IS_DELETED";
export const TEAM_CREATION_REQUEST = "TEAM_CREATION_REQUEST";
export const TEAM_CREATED = "TEAM_CREATED";
export const TEAM_DELETED = "TEAM_DELETED";
export const TEAM_SELECTED = "TEAM_SELECTED";
export const TEAM_FOLLOWED = "TEAM_FOLLOWED";
export const TEAM_UNFOLLOWED = "TEAM_UNFOLLOWED";
export const TEAM_LEADERBOARD_LOADED = "TEAM_LEADERBOARD_LOADED";
export const IS_FOLLOWED = "IS_FOLLOWED";
export const NOT_FOLLOWED = "NOT_FOLLOWED";
export const SET_ORGANIZATIONS_FOLLOWED_LIST =
  "SET_ORGANIZATIONS_FOLLOWED_LIST";
export const SET_TEAMS_FOLLOWED_LIST = "SET_TEAMS_FOLLOWED_LIST";
export const TEAM_ADMIN_REQUEST_LOADING = "TEAM_ADMIN_REQUEST_LOADING";
export const TEAM_ADMIN_REQUEST_SENT = "TEAM_ADMIN_REQUEST_SENT";
export const TEAM_ADMIN_REQUESTS_LOADED = "TEAM_ADMIN_REQUESTS_LOADED";
export const TEAM_ADMIN_REQUEST_UPDATED = "TEAM_ADMIN_REQUEST_UPDATED";
export const TEAM_ADMIN_EDIT_SELECTED = "TEAM_ADMIN_EDIT_SELECTED";
export const LOAD_TEAM_ADMIN_REQUESTS = "LOAD_TEAM_ADMIN_REQUESTS";
export const TEAM_ADMIN_REQUESTS_PROFILE_LOADED =
  "TEAM_ADMIN_REQUESTS_PROFILE_LOADED";
export const TEAM_ADMIN_REQUESTS_PROFILE_RESETED =
  "TEAM_ADMIN_REQUESTS_PROFILE_RESETED";
export const RESET_TEAM_ADMIN_REQUEST_LIST = "RESET_TEAM_ADMIN_REQUEST_LIST";
export const RESET_TEAM_REDUCER = "RESET_TEAM_REDUCER";
export const TEAM_LEADERBOARD_DELETED = "TEAM_LEADERBOARD_DELETED";
export const TEAM_LEADERBOARD_LOADING = "TEAM_LEADERBOARD_LOADING";

export const AMENITI_ADDED = "AMENITI_ADDED";
export const AMENITI_REMOVED = "AMENITI_REMOVED";
export const EVENT_CREATED = "EVENT_CREATED";
export const EVENT_UPDATED = "EVENT_UPDATED";
export const EVENT_SELECTED = "EVENT_SELECTED";
export const RESET_EVENT_UPDATED = "RESET_EVENT_UPDATED";
export const RESET_EVENT_SELECTED = " RESET_EVENT_SELECTED";
export const RESET_EVENT_IS_CREATED = "RESET_EVENT_IS_CREATED";
export const EVENT_DELETED = "EVENT_DELETED";
export const RESET_EVENT_DELETED = "RESET_EVENT_DELETED";
export const EVENT_LINK_UPDATED = "EVENT_LINK_UPDATED";
export const LOADING_EVENTS = "LOADING_EVENTS";
export const EVENT_LIST_LOADED = "EVENT_LIST_LOADED";
export const EVENT_ATTENDING_LIST_LOADED = "EVENT_ATTENDING_LIST_LOADED";
export const FILTER_UPDATED = "FILTER_UPDATED";
export const FILTER_RESETED = "FILTER_RESETED";
export const USER_SELECTED = "USER_SELECTED";
export const ACTIVE_EVENT_INDEX_SET = "ACTIVE_EVENT_INDEX_SET";
export const TRIGGER_SCROLL_TO_LATEST_EVENT = " TRIGGER_SCROLL_TO_LATEST_EVENT";
export const EVENT_STREAM_LINK_SELECTED = "EVENT_STREAM_LINK_SELECTED";

export const SPORTS_LOADED = "SPORTS_LOADED";

export const START_TUTORIAL = "START_TUTORIAL";
export const COMPLETE_TUTORIAL = "COMPLETE_TUTORIAL";
export const NEXT_TUTORIAL_STEP = "NEXT_TUTORIAL_STEP";
